version: "3.8"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
