server:
  port: 8081

spring:
  devtools:
    restart:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notificationdb
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

logging:
  level:
    root: INFO
    org.springframework.cloud.openfeign: DEBUG
