server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notificationdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest