server:
  port: 8081

spring:
  devtools:
    restart:
      enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notificationdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
